# Generated by Django 5.1.6 on 2025-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('session_id', models.TextField(blank=True, null=True)),
                ('user_input', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
