# Generated by Django 5.1.6 on 2025-02-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_company_id_model_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='company_name',
            field=models.TextField(blank=True, default='Aisha', null=True),
        ),
    ]
